#theme: jekyll-theme-cayman
#theme: jekyll-theme-midnight
#theme: jekyll-theme-slate
theme: jekyll-theme-minimal

title: "@iHdkzまとめ"
description: "importer iHdkzのホストサイト"
logo: img/Ramon_Llull.jpg

#twitter:
#  username: 
